//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;

public partial class TB_CLIENTE
{
    public int ID_CLIENTE { get; set; }
    public string NM_CLIENTE { get; set; }
    public string DS_ENDERECO { get; set; }
    public string NR_TELEFONE { get; set; }
    public string DS_EMAIL { get; set; }
}
