//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Empresario.SisCliente.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_CLIENTE
    {
        public int ID_CLIENTE { get; set; }
        public string NM_CLIENTE { get; set; }
        public string DS_ENDERECO { get; set; }
        public string NR_TELEFONE { get; set; }
        public string DS_EMAIL { get; set; }
    }
}
